# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-banco
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

services:
- type: worker
  name: robo-de-arbitragem
  env: node
  region: oregon
  plan: free
  buildCommand: |
    npm install
    npm run build:tracker
  startCommand: |
    node websocket-server.js & 
    node monitor.js
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false

version: "1"