# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-banco
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

services:
- type: web
  name: robo-de-arbitragem
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && npm install typescript @types/node --save && npm run build
  startCommand: next start
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false
    - key: NEXT_PUBLIC_WS_URL
      value: wss://robo-de-arbitragem-tracker.onrender.com
  healthCheckPath: /

- type: web
  name: robo-de-arbitragem-tracker
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && tsc websocket-server.ts --outDir dist
  startCommand: node dist/websocket-server.js
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false
  healthCheckPath: /health

version: "1"