# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-db
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: starter
  region: oregon
  ipAllowList: []
  postgresMajorVersion: "16"
  postDeploy: npx prisma migrate deploy

services:
- type: web
  name: arbitragem-render-03
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && npx prisma generate && npm run build
  startCommand: npm start
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-db
        property: connectionString
    - key: NODE_ENV
      value: production

- type: cron
  name: spread-monitor
  env: node
  schedule: "*/30 * * * *"  # Roda a cada 30 minutos
  buildCommand: npm install && npx prisma generate && npm run build:cron
  startCommand: npm run start:cron
  instanceType: starter  # Instância mais básica (512MB RAM, 0.5 CPU)
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-db
        property: connectionString
    - key: NODE_ENV
      value: production
    - key: GATEIO_API_KEY
      sync: false  # Indica que este valor será definido manualmente no dashboard
    - key: GATEIO_API_SECRET
      sync: false
    - key: MEXC_API_KEY
      sync: false
    - key: MEXC_API_SECRET
      sync: false

- type: web
  name: spread-collector
  env: node
  buildCommand: |
    npm install
    cd scripts
    npx tsc --project tsconfig.json
  startCommand: node scripts/dist/spread-monitor.js
  plan: free
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-db
        property: connectionString

- type: cron
  name: spread-monitor-health
  env: node
  buildCommand: npm install && npm run build:monitor
  startCommand: node dist/scripts/monitor-cron.js
  schedule: "*/5 * * * *"
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-db
        property: connectionString

version: "1"