# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-banco
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
  postDeploy: npm run db:setup && npm run prisma:deploy
- name: postgres
  plan: free
  ipAllowList: []
  postDeploy: npm run db:setup
services:
- type: web
  name: robo-de-arbitragem
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && npm run db:setup && npm run build
  startCommand: npm start
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-banco
        property: connectionString
    - key: NEXT_PUBLIC_WEBSOCKET_URL
      value: wss://robo-de-arbitragem-tracker.onrender.com
    - key: BINANCE_API_KEY
      sync: false
    - key: BINANCE_SECRET
      sync: false
    - key: MEXC_API_KEY
      sync: false
    - key: MEXC_SECRET
      sync: false
    - key: GATE_API_KEY
      sync: false
    - key: GATE_SECRET
      sync: false
  autoDeploy: true
  branch: default

- type: web
  name: robo-de-arbitragem-tracker
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && npm run db:setup && npm run build:tracker
  startCommand: npm run start:tracker
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-banco
        property: connectionString
    - key: BINANCE_API_KEY
      sync: false
    - key: BINANCE_SECRET
      sync: false
    - key: MEXC_API_KEY
      sync: false
    - key: MEXC_SECRET
      sync: false
    - key: GATE_API_KEY
      sync: false
    - key: GATE_SECRET
      sync: false
  autoDeploy: true
  branch: default

- type: worker
  name: arbitragem-cleanup
  env: node
  plan: free
  buildCommand: npm install && npm run db:setup
  startCommand: npm run cleanup:schedule
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-banco
        property: connectionString

- type: worker
  name: arbitragem-render
  env: node
  region: oregon
  plan: standard
  buildCommand: |
    export NODE_OPTIONS="--max_old_space_size=2048"
    rm -rf node_modules
    rm -rf dist
    npm ci
    npm run prisma:generate
    npm run build:server
  startCommand: node --max-old-space-size=2048 dist/src/spread-monitor.js
  envVars:
    - key: NODE_ENV
      value: production
    - key: NODE_VERSION
      value: 18.17.0
    - key: PRISMA_CLI_QUERY_ENGINE_TYPE
      value: binary
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-banco
        property: connectionString
    - key: MEXC_API_KEY
      sync: false
    - key: MEXC_SECRET
      sync: false
    - key: GATE_API_KEY
      sync: false
    - key: GATE_SECRET
      sync: false
  autoDeploy: true
  branch: master

version: "1"