# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-banco
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

services:
- type: web
  name: robo-de-arbitragem
  env: node
  region: oregon
  plan: free
  buildCommand: |
    npm install
    npm run build:tracker
  startCommand: node monitor.js
  envVars:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "10000"
    - key: DATABASE_URL
      sync: false
    - key: NODE_VERSION
      value: "18.17.0"
    - key: NEXT_PUBLIC_WEBSOCKET_URL
      value: "wss://robo-de-arbitragem-5n8k.onrender.com"

version: "1"