# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-db
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
  postDeploy: npx prisma migrate deploy

services:
- type: web
  name: arbitragem-web
  env: node
  plan: free
  buildCommand: npm install && npm run build
  startCommand: npm start
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-db
        property: connectionString
    - key: NEXT_PUBLIC_WEBSOCKET_URL
      value: wss://arbitragem-worker.onrender.com
    - key: PORT
      value: 10000
    - key: HOSTNAME
      value: 0.0.0.0

- type: worker
  name: arbitragem-worker
  env: node
  plan: free
  buildCommand: npm install && npm run build:worker
  startCommand: npm run start:worker
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: arbitragem-db
        property: connectionString
    - key: PORT
      value: 8080
    - key: NODE_ENV
      value: production
    - key: HOSTNAME
      value: 0.0.0.0

version: "1"