# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-banco
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

services:
- type: web
  name: robo-de-arbitragem
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && npm install typescript @types/node --save && npm run build
  startCommand: next start
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false
    - key: NEXT_PUBLIC_WS_URL
      value: wss://robo-de-arbitragem-tracker.onrender.com
  healthCheckPath: /
  autoDeploy: true

- type: web
  name: robo-de-arbitragem-tracker
  env: node
  region: oregon
  plan: free
  buildCommand: npm install && npm run build
  startCommand: npm run start
  autoDeploy: true
  envVars:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: 10000
  headers:
    - path: /*
      name: Access-Control-Allow-Origin
      value: "*"
    - path: /*
      name: Access-Control-Allow-Methods
      value: "GET, POST, OPTIONS"
    - path: /*
      name: Access-Control-Allow-Headers
      value: "Content-Type"
  healthCheckPath: /health
  healthCheckTimeout: 100

version: "1"