# Exported from Render on 2025-06-10T21:42:54Z
databases:
- name: arbitragem-banco
  databaseName: arbitragem_banco
  user: arbitragem_banco_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: robo-de-arbitragem
  env: node
  region: oregon
  plan: free
  branch: main
  buildCommand: npm install && npm run prisma:deploy && npm run build
  startCommand: npm run start
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: arbitragem-banco
      property: connectionString
version: "1" 